-- This configuration is generated by matugen
-- Changing these variables with matugen still enabled will overwrite them.

image = "/home/rites/Pictures/Wallpapers/art-green-forest.jpg"

color_background = "rgba(0f1511ff)"

color_error = "rgba(ffb4abff)"

color_error_container = "rgba(93000aff)"

color_inverse_on_surface = "rgba(2c322eff)"

color_inverse_primary = "rgba(216a4dff)"

color_inverse_surface = "rgba(dee4deff)"

color_on_background = "rgba(dee4deff)"

color_on_error = "rgba(690005ff)"

color_on_error_container = "rgba(ffdad6ff)"

color_on_primary = "rgba(003825ff)"

color_on_primary_container = "rgba(a9f2cdff)"

color_on_primary_fixed = "rgba(002114ff)"

color_on_primary_fixed_variant = "rgba(005138ff)"

color_on_secondary = "rgba(1f352aff)"

color_on_secondary_container = "rgba(cfe9d9ff)"

color_on_secondary_fixed = "rgba(0a1f16ff)"

color_on_secondary_fixed_variant = "rgba(364b40ff)"

color_on_surface = "rgba(dee4deff)"

color_on_surface_variant = "rgba(bfc9c1ff)"

color_on_tertiary = "rgba(073543ff)"

color_on_tertiary_container = "rgba(c1e9fbff)"

color_on_tertiary_fixed = "rgba(001f29ff)"

color_on_tertiary_fixed_variant = "rgba(244c5bff)"

color_outline = "rgba(8a938cff)"

color_outline_variant = "rgba(404943ff)"

color_primary = "rgba(8dd5b2ff)"

color_primary_container = "rgba(005138ff)"

color_primary_fixed = "rgba(a9f2cdff)"

color_primary_fixed_dim = "rgba(8dd5b2ff)"

color_scrim = "rgba(000000ff)"

color_secondary = "rgba(b4ccbdff)"

color_secondary_container = "rgba(364b40ff)"

color_secondary_fixed = "rgba(cfe9d9ff)"

color_secondary_fixed_dim = "rgba(b4ccbdff)"

color_shadow = "rgba(000000ff)"

color_source_color = "rgba(2e624bff)"

color_surface = "rgba(0f1511ff)"

color_surface_bright = "rgba(353b37ff)"

color_surface_container = "rgba(1b211dff)"

color_surface_container_high = "rgba(252b28ff)"

color_surface_container_highest = "rgba(303632ff)"

color_surface_container_low = "rgba(171d19ff)"

color_surface_container_lowest = "rgba(0a0f0cff)"

color_surface_dim = "rgba(0f1511ff)"

color_surface_tint = "rgba(8dd5b2ff)"

color_surface_variant = "rgba(404943ff)"

color_tertiary = "rgba(a5ccdeff)"

color_tertiary_container = "rgba(244c5bff)"

color_tertiary_fixed = "rgba(c1e9fbff)"

color_tertiary_fixed_dim = "rgba(a5ccdeff)"
